[project]
name = "Bit2Stacks"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/Bit2Stacks/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.Bit2Stacks]
path = "contracts/Bit2Stacks.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
